### ISSUE TITLE
Declaration of JWK X509CertificateChainParameter's constructor must be compatible with JWX ArrayParameterValue's constructor

### ISSUE THREAD

**Issue by thtg88** [sop/jwx#1]
Hi there, thanks for the great package!

Trying to instantiate a JWK `X509CertificateChainParameter` throws the following error on PHP v8.0.10:

> Declaration of Sop\JWX\JWK\Parameter\X509CertificateChainParameter::__construct(string ...$certs) must be compatible with Sop\JWX\Parameter\Feature\ArrayParameterValue::__construct(...$values)

I wonder if the X509 parameter's constructor definition can be changed to something like:
```php
/**
 * Constructor.
 *
 * @param string[] $certs Base64 encoded DER certificates
 */
public function __construct(...$certs)
{
    /** @var string $cert */
    foreach ($certs as $cert) {
        if (!Base64::isValid($cert)) {
            throw new \UnexpectedValueException(
                'Certificate must be base64 encoded.');
        }
    }
    parent::__construct(self::PARAM_X509_CERTIFICATE_CHAIN, $certs);
}
```

Happy to open a PR with the change :)

**Comment by sop** [comment]
Hi!

Thanks for reporting the error. I fixed some minor issues with stricter PHP 8 typings and have now published a new version.

**Comment by thtg88** [comment]
Can confirm this works with the update version - thank you! :)
