### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by TomTervoort** [sop/jwx#2]
Hi,

I discovered a vulnerability in JWX that I would like to report. However, I can't seem to find an appropriate (private) channel to contact the maintainer for responsible disclosure.

@sop How would you like to receive this report?

**Comment by sop** [comment]
Hi!

I've added email address to my [profile](https://github.com/sop).

**Comment by TomTervoort** [comment]
Thanks! I'll reach out to you via mail.

**Comment by kenjis** [comment]
Hi, this vulnerability was fixed or not?

**Comment by sop** [comment]
> Hi, this vulnerability was fixed or not?

Hi! It was fixed in master branch but i never got to push a release. I've just released a new tag, which is a major release by semantic versioning, so please update your dependencies if necessary. Technically this is a breaking change if someone was relying on vulnerable algorithms in question.
